name: Quality
on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Check out code
        uses: actions/checkout@v2

#      - name: Install dependencies
#        run: |
#          go mod download
      - name: Run Unit tests
        run: |
          go test -coverprofile=./coverage.txt ./...
#      - name: Run Gosec Security Scanner
#        run: |
#          go install github.com/securego/gosec/v2/cmd/gosec@latest
#          gosec -no-fail -fmt=sonarqube -out report.json ./...
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}